### ISSUE TITLE
ES3 Implementation

### ISSUE THREAD

**Issue by audinue** [justinfagnani/mixwith.js#11]
IE6 compatible. Just for fun. Nothing serious. Tell me what you think about this :smile:

```javascript
function Mixin1 (superClass) {
  function Mixin1 () {
    // Passing constructor arguments
    superClass.apply(this, arguments)
  }
  Mixin1.prototype = new superClass()
  // Calling super class method
  Mixin1.prototype.callSuperClassMethodExample = function () {
    superClass.prototype.superClassMethod()
    return this
  }
  return Mixin1
}

function Mixin2 (superClass) {
  function Mixin2 () {
    superClass.apply(this, arguments)
  }
  Mixin2.prototype = new superClass()
  Mixin2.prototype.anotherMixinMethod = function () {
    alert('Hello from mixin!')
  }
  return Mixin2
}

// Composing mixins
function Mixin3 (superClass) {
  return Mixin2(Mixin1(superClass))
}

// Test it
var Foo = (function () {
  function Foo () {
  }
  Foo.prototype.superClassMethod = function () {
    alert('Hello from superClass!')
  }
  return Mixin3(Foo)
}())

new Foo().callSuperClassMethodExample().anotherMixinMethod()
```

**Comment by trusktr** [comment]
>   `Mixin1.prototype = new superClass()`

I don't think you should use `new` there, since that might run logic meant for the instance when the instance is created, not when the class is defined. I think you can use Object.create ([polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create)), if that works in ES3?

**Comment by audinue** [comment]
That's right.

**Comment by trusktr** [comment]
I was thinking about this a little more. The real reason to not instantiate the super class constructor automatically is because this prevents the extending developer from being able to control when the super constructor is called in the new subclass. They may assume that the constructor has not already been called and may call the constructor a second time in their extending class, which could possibly bugs.

But, if you're calling `new Something` as part of the implementation of how the mixin works, then that's fine, but the super class should be left alone because the super class is being passed in by the developer using the mixin and defining a class that extends the super class, so we want to let the developer have control over how the class he/she is extending runs.

**Comment by trusktr** [comment]
I was thinking about this a little more. The real reason to not instantiate the super class constructor automatically is because this prevents the extending developer from being able to control when the super constructor is called in the new subclass. They may assume that the constructor has not already been called and may call the constructor a second time in their extending class, which could possibly cause bugs.

But, if you're calling `new Something` as part of the implementation of how your mixin tool works, and placing that somewhere in the prototype chain, then that's fine, but the super class should be left alone because the super class is being passed in by the developer using the mixin tool and defining a class that extends the super class (with mixins), so we want to let the developer have control over how the subclass and superclass are designed to work without the mixin tool doing unexpected things behind the scenes.

**Comment by justinfagnani** [comment]
I like this :)

As opposed to `new superclass()`, you can do `superclass.call(this)`.

Babel produces code that's basically similar:

```javascript
var M = function M(superclass) {
  return function (_superclass) {
    _inherits(_class, _superclass);

    function _class() {
      _classCallCheck(this, _class);

      return _possibleConstructorReturn(this, _superclass.apply(this, arguments));
    }

    _class.prototype.foo = function foo() {
      return 'foo';
    };

    return _class;
  }(superclass);
};
```

I'm going to close this and soon figure out whether a version should be distributed that's compiled to ES5.

**Comment by paulmelnikow** [comment]
Love this pattern!

Did you end up making this ES5-compiled implementation? I'm writing a mixin for an ES5 library and it'd be really useful. Wondering if I should roll my own.

**Comment by trusktr** [comment]
Just thought I'd share, here's how I make my mixin classes: https://github.com/trusktr/infamous/blob/master/src/motor/Observable.js

In particular, note that the exported class can be used as a mixin, or as a normal class, and also note  what I'm doing with `Symbol.hasInstance` which is what makes `instanceof` work regardless of which way you use the class/mixin.

You'd use it like this:

```js
import Observable from 'infamous/motor/Observable'

// extend directly like a normal class
class Foo extends Observable { ... }

console.log(Foo instanceof Observable) // true
```

or

```js
import Observable from 'infamous/motor/Observable'

class Foo { ... }

// or use it as a mixin
class Bar extends Observable.mixin(Foo) { ... }

console.log(Foo instanceof Observable) // true
```

**Comment by trusktr** [comment]
@paulmelnikow I just compile mine to ES5 with Babel currently. You could also try [Bublé](https://buble.surge.sh), which is much more lightweight and produces hand-written-like output, with [some limitations](https://buble.surge.sh/guide/#unsupported-features). If you can stay within limitations, Buble might be an easy way to write your using `class` and transpile it for ES5.

**Comment by paulmelnikow** [comment]
Thanks for that. Interesting ideas.

What I'm looking for is more of a backport of the pattern to ES5. The idea is to adhere to the pattern as much as possible, so that it is easy to move to this pattern and library once the base library has switched to classes. I'd rather not introduce a transpiler at this stage, since it makes things more complicated than necessary.

**Comment by trusktr** [comment]
@paulmelnikow 

> I'd rather not introduce a transpiler at this stage, since it makes things more complicated than necessary.

I agree, which is why I mentioned Bublé, it really outputs really really non-complicated code. It will give you code that is very similar to what you'll write by hand, _literally_.

To get started by hand though, you can easily write class-factory mixin for ES5, f.e. a starting point:

```js
function FooMixin(base) {
  if (typeof base != 'function') throw new Error('not function')

  // class Foo
  function Foo() {
    // constructor logic for Foo class
  }

  // extends base
  Foo.prototype = Object.create(base.prototype)

  Foo.prototype.someMethod = function() { ... }

  return Foo

  // implement Symbol.hasInstane-like stuff here.
}
```

**Comment by trusktr** [comment]
@paulmelnikow Here's my [Observable class transpiled with Buble](https://buble.surge.sh/#%0Aconst%20instanceofSymbol%20%3D%20Symbol('instanceofSymbol')%0A%0Aconst%20ObservableMixin%20%3D%20base%20%3D%3E%20%7B%0A%20%20%20%20class%20Observable%20extends%20base%20%7B%0A%0A%20%20%20%20%20%20%20%20constructor(options%20%3D%20%7B%7D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20super(options)%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20on(eventName%2C%20callback)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this._eventMap)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this._eventMap%20%3D%20new%20Map%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this._eventMap.has(eventName))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this._eventMap.set(eventName%2C%20%5B%5D)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(typeof%20callback%20%3D%3D%20'function')%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20this._eventMap.get(eventName).push(callback)%0A%20%20%20%20%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20throw%20new%20Error('Expected%20a%20function%20in%20callback%20argument%20of%20Observable%23on.')%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20off(eventName%2C%20callback)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this._eventMap%20%7C%7C%20!this._eventMap.has(eventName))%20return%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20callbacks%20%3D%20this._eventMap.get(eventName)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(callbacks.indexOf(callback)%20%3D%3D%3D%20-1)%20return%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20callbacks.splice(callbacks.indexOf(callback)%2C%201)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(callbacks.length%20%3D%3D%3D%200)%20this._eventMap.delete(eventName)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(this._eventMap.size%20%3D%3D%3D%200)%20this._eventMap%20%3D%20null%0A%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20triggerEvent(eventName%2C%20data)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(!this._eventMap%20%7C%7C%20!this._eventMap.has(eventName))%20return%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20const%20callbacks%20%3D%20this._eventMap.get(eventName)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(let%20i%3D0%2C%20len%3Dcallbacks.length%3B%20i%3Clen%3B%20i%2B%3D1)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20callbacks%5Bi%5D(data)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20Object.defineProperty(Observable%2C%20Symbol.hasInstance%2C%20%7B%0A%20%20%20%20%20%20%20%20value%3A%20function(obj)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(this%20!%3D%3D%20Observable)%20return%20Object.getPrototypeOf(Observable)%5BSymbol.hasInstance%5D.call(this%2C%20obj)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20currentProto%20%3D%20obj%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20while(currentProto)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20desc%20%3D%20Object.getOwnPropertyDescriptor(currentProto%2C%20%22constructor%22)%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(desc%20%26%26%20desc.value%20%26%26%20desc.value.hasOwnProperty(instanceofSymbol))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20true%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20currentProto%20%3D%20Object.getPrototypeOf(currentProto)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20false%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%0A%0A%20%20%20%20Observable%5BinstanceofSymbol%5D%20%3D%20true%0A%0A%20%20%20%20return%20Observable%0A%7D%0A%0Aconst%20Observable%20%3D%20ObservableMixin(class%7B%7D)%0AObservable.mixin%20%3D%20ObservableMixin%0A), it is almost the same code.

It just leaves `Symbol.hasInstance` in place, but I don't know if it will work in older browsers that don't read the `Symbol.hasInstance` property on constructor when using `instanceof`.

**Comment by paulmelnikow** [comment]
That's a good snippet. Looks similar to what I have, except:
```js
function IcedFrisbyNock () {
  superClass.apply(this, arguments);
}
```

I also want to transfer statics:

```js
// Transfer statics.
Object.assign(FooMixin, superClass);
```

I haven't tested that in all cases (the case I'm using is more complicated), though I think it should work as long as it comes before the assignment of `prototype`.

Bublé is cool to know about. I should have been clearer, though. I mean that I don't want a complicated toolchain.

**Comment by trusktr** [comment]
> `superClass.apply(this, arguments);`
> `// Transfer statics.`

Oh yep, forgot about those. I think you meant `Object.assign(IcedFrisbyNock, superClass);`, but yeah, good point, ES6 classes do that automatically too.
